### ISSUE TITLE
User Data Streams

### ISSUE THREAD

**Issue by mohammad-rj** [zhouaini528/binance-php#15]
can u plz add an example of User Data Streams

**Comment by zhouaini528** [comment]
[User Data Streams](https://github.com/zhouaini528/binance-php/blob/master/tests/spot/listen_key.php)
```php
$binance=new Binance($key,$secret);
try {
    $result=$binance->user()->postUserDataStream();
    print_r($result);
}catch (\Exception $e){
    print_r(json_decode($e->getMessage(),true));
}

```

**Comment by mohammad-rj** [comment]
tanks for answer
postUserDataStream just give me a  [listenKey] => xxx

**Comment by zhouaini528** [comment]
[Here is an example](https://gitee.com/ding_yuan_tai_fu?invite=b9d8e0702134bacddd04628c0ac117eb18101adc76ecaf528e7cde0b62298f89083caf609d592eb519edbdc670902e5616e6879e9e6b7295)

When the private channel is successfully established, all user data will be subscribed by default.

For the type of private channel, the queue data is saved 100 by default.

```php
$binance->config([
    //Do you want to enable local logging,default false
    'log'=>['filename'=>'spot'],

    //Daemons address and port,default 0.0.0.0:2208
    'global'=>'127.0.0.1:22088',

    //Number of messages WS queue shuold hold, default 100
    'queue_count'=>100,

    //baseurl
    'baseurl'=>'ws://stream.binance.com:9443',
]);

$binance->keysecret([
    'key'=>'xxxxxxxxx',
    'secret'=>'xxxxxxxxx',
]);
        
//Subscribe to all private channels by default
$binance->subscribe();
```

**Comment by mohammad-rj** [comment]
thank you very much for your response

I tested several models.
I will summarize the result here.
Maybe it will help to understand others faster. (Or if you misunderstand, let me know)

we have 3 base url for 3 market type [spot, usdt future, coin future]
'baseurl'=>'ws://stream.binance.com:9443',//default //spot
'baseurl'=>'ws://fstream.binance.com', //usdt future
'baseurl'=>'ws://dstream.binance.com', //coin future

we must first start "websocket server daemon" (channel) (we can see listen on public or private data) (we can see listen on private data only when we subscribe with our key and secret api keys)

after that we must run a client daemon to start getinge data
When the private channel is successfully established, all user data will be subscribed by default.

noob fact:
with ws://stream.binance.com:9443 we can just get stop market data
and 
with ws://fstream.binance.com we can just get usdt future market data
