### ISSUE TITLE
WebSockets Disconnecting

### ISSUE THREAD

**Issue by NumairAwan** [zhouaini528/binance-php#21]
Hi, whenever i start the websockets stream getting strange error. It was working fine few days back but suddenly starts getting this this.

![image](https://user-images.githubusercontent.com/62851858/120254903-4b60eb00-c2a4-11eb-8417-57ce0ca6491f.png)

**Comment by zhouaini528** [comment]
Hello, I haven't met you here. Is there any problem after you restart? How long will it last?

**Comment by NumairAwan** [comment]
It's disconnecting instantly, i tried to connect from this website https://www.piesocket.com/websocket-tester but still getting disconnect issue.

I don't know if the problem is from binance side or some kind of firewall issue. You can check that spot market stream is getting disconnecting instantly but Future derivatives stream sometimes works and sometimes not.

SPOT STREAM : wss://stream.binance.com:9443
FUTURE DERIVATIVES : wss://fstream.binance.com

**Comment by NumairAwan** [comment]
Fixed it, it was a firewall (tcp ports) issue thanks for your quick response and awesome lib.
