### ISSUE TITLE
update fapi to v2

### ISSUE THREAD

**Issue by ItsNash0** [zhouaini528/binance-php#24]
currently all futures api requests go to fapi v1, but we are on v2

**Comment by ItsNash0** [comment]
#25

**Comment by zhouaini528** [comment]
Thank you for your commits

**Comment by llomgui** [comment]
Hello,

V2 endpoint does not work for most of the api requests.
I always get an error 404 on postOrder, the only way to make it work is to update v2 to v1.

Can you confirm on your side @ItsNash0 ?

Thank you
