### ISSUE TITLE
Error: multi workers init in one php file are not support

### ISSUE THREAD

**Issue by DaviCieluck** [zhouaini528/binance-php#3]
Hello, I'm a beginner

I'm doing the test in websocket spot Only the server, as recommended.

But the error returns:

----------------------- WORKERMAN -----------------------------
Workerman version:4.0.18          PHP version:7.3.12
------------------------ WORKERS -------------------------------
worker               listen                              processes status
@@@ Error: multi workers init in one php file are not support @@@
@@@ See http://doc.workerman.net/faq/multi-woker-for-windows.html @@@
none                 none                                1         [ok]
PHP Warning:  stream_socket_client(): unable to connect to tcp://0.0.0.0:2208 (O endereo solicitado no  vlido no contexto.
) in D:\p_local\wsTeste\vendor\workerman\globaldata\src\Client.php on line 66

How to solve ?

Tanks!

**Comment by zhouaini528** [comment]
Are you a windos or linux environment? Must be executed in linux.

**Comment by DaviCieluck** [comment]
Windows system. Ok. Tanks for answering.
