### ISSUE TITLE
Question : Cannot use Workerman\Lib\Timer as Timer because the name is already in use

### ISSUE THREAD

**Issue by yobogs** [zhouaini528/binance-php#5]
Hi,

I use this code on my client : 

`$binance=new BinanceWebSocket();

$binance->config([
   ...
    'baseurl'=>'ws://fstream.binance.com',//usdt future
...
]);

	$binance->subscribe(['xrpusdt@bookTicker']);
	$binance->getSubscribe(['xrpusdt@bookTicker'], function ($data){
		print_r($data);
	}, true);
`

I have this error "Cannot use Workerman\Lib\Timer as Timer because the name is already in use" because i put "true" 

Have you an idea why i have this error ?

Thanks for your help

**Comment by zhouaini528** [comment]
You try to execute the original php code, for example /test/demo. This error indicates that the client has been started, it may be that the port is already occupied and cannot be used multiple times in a process

**Comment by zhouaini528** [comment]
There is also an error situation in which the workerman must be killed during the tuning process.

**Comment by yobogs** [comment]
Thanks for your help

I don't understand how to use the script.

- I have a server started with /php server.php start -d -> Work fine
- I have a client file (code in my question) 

My goal : have a php script to refresh the price of coin each x secondes.

Have you an advice to do this based on your script

Thank you ;-)

**Comment by zhouaini528** [comment]
You try to change true to false
```php
$binance->subscribe(['xrpusdt@bookTicker']);
$binance->getSubscribe(['xrpusdt@bookTicker'], function ($data){
	print_r($data);
},false);
```
Can the data be obtained in this way?

You can design your own daemon instead of following my demo.

**Comment by yobogs** [comment]
Yes it's work but i just not undestand why i have "Alarm clock" at end of my print_r

`Array
(
    [xrpusdt@bookTicker] => Array
        (
            [stream] => xrpusdt@bookTicker
            [data] => Array
                (
                    [e] => bookTicker
                    [u] => 251396715357
                    [s] => XRPUSDT
                    [b] => 0.4699
                    [B] => 67194.9
                    [a] => 0.4700
                    [A] => 37007.4
                    [T] => 1615367072069
                    [E] => 1615367072073
                )

        )

)
Alarm clock`

**Comment by zhouaini528** [comment]
I don't understand what "Alarm clock" means？Does printing output "Alarm clock"?

**Comment by yobogs** [comment]
yes ;-)
[https://ibb.co/5sPGNWh](url)

**Comment by zhouaini528** [comment]
I just tested and did not find the problem you said.
![_20210310085720](https://user-images.githubusercontent.com/5442664/110606477-3143cf00-81c5-11eb-98d7-9100add87096.png)

**Comment by yobogs** [comment]
Ok i will search
Thanks for your help and for your script :-)
