### ISSUE TITLE
Binance no longer support Futures v1

### ISSUE THREAD

**Issue by hk743kfjw** [zhouaini528/binance-php#52]
On Binance Change Log said:
> ### 2023-06-28
> Notice:
> REST
> The following endpoints will no longer be supported from 2023-07-15:
> 
> - GET /fapi/v1/account
> - GET /fapi/v1/balance
> - GET /fapi/v1/positionRisk
> 
> Please switch to corresponding v2 endpoints:
> 
> - GET /fapi/v2/account
> - GET /fapi/v2/balance
> - GET /fapi/v2/positionRisk

Adding 'v2' to options not working. 
The orders do not placing with this option:
```
$binance->setOptions([
    'version' => 'v2'
]);
```

**Comment by zhouaini528** [comment]
> 
I'll check it out

**Comment by zhouaini528** [comment]
> On Binance Change Log said:
> 
> > ### 2023-06-28
> > Notice:
> > REST
> > The following endpoints will no longer be supported from 2023-07-15:
> > 
> > * GET /fapi/v1/account
> > * GET /fapi/v1/balance
> > * GET /fapi/v1/positionRisk
> > 
> > Please switch to corresponding v2 endpoints:
> > 
> > * GET /fapi/v2/account
> > * GET /fapi/v2/balance
> > * GET /fapi/v2/positionRisk
> 
> Adding 'v2' to options not working. The orders do not placing with this option:
> 
> ```
> $binance->setOptions([
>     'version' => 'v2'
> ]);
> ```
![2023-07-19 14-29-28屏幕截图](https://github.com/zhouaini528/binance-php/assets/5442664/6d79df05-9b1a-4db3-b56f-c181242f9429

![2023-07-19 14-26-37屏幕截图](https://github.com/zhouaini528/binance-php/assets/5442664/f26bed30-54be-4afd-9b0b-8da399567021)
)

the test works

**Comment by hk743kfjw** [comment]
So now, in order to check the account and balance, we have to switch the options to version 2. And after that, before placing an order, we need to switch the version to 1. Right?

**Comment by zhouaini528** [comment]
Yes. In fact, I also think this is very troublesome, because some people have used v1 before, and some people still use v3, and spot and future are mixed versions, so this method is adopted.
