### ISSUE TITLE
server.php and client.php

### ISSUE THREAD

**Issue by tcolonel** [zhouaini528/binance-php#6]
Hi there.

> If you want to test, you can "php server.php start" immediately outputs the log at the terminal.
> 
> If you want to deploy, you can "php server.php start -d" enables resident process mode, and enables "log=>true" to view logs.

Where is `server.php` located (I don't see it at `src` folder)? Or I need to use example (`Server initialization must be started in cli mode.`)?

And what about `client.php`? Or I need to use example (`Client side initialization.`)?

Thanks.

**Comment by zhouaini528** [comment]
https://github.com/zhouaini528/binance-php/tree/master/tests/websocket

![20210310085720](https://user-images.githubusercontent.com/5442664/110559163-b1931180-817e-11eb-8d76-7660979cbefa.png)


Need to be executed in linux command line (CLI) mode
