### ISSUE TITLE
How to place OCO order?

### ISSUE THREAD

**Issue by NumairAwan** [zhouaini528/binance-php#8]
Hi, Does your API support OCO orders?

**Comment by zhouaini528** [comment]
Hello, I don't understand what OCO is?

**Comment by zhouaini528** [comment]
It is currently not supported, and I will complete it within this week. Please wait

**Comment by zhouaini528** [comment]
It is currently not supported, and I will complete it within this week. Please wait

**Comment by NumairAwan** [comment]
Ok thank you very much. I will wait for this update.

**Comment by zhouaini528** [comment]
Hi ,To see

[Trade https://github.com/zhouaini528/binance-php/blob/master/tests/spot/trade.php#L76](https://github.com/zhouaini528/binance-php/blob/master/tests/spot/trade.php#L76)

[User https://github.com/zhouaini528/binance-php/blob/master/tests/spot/user.php#L59](https://github.com/zhouaini528/binance-php/blob/master/tests/spot/user.php#L59)

If you find any missing API, please let me know.

**Comment by NumairAwan** [comment]
Thank you very much bro.
